apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-py-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-py-client
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-py-client
subjects:
- kind: ServiceAccount
  name: k8s-py-client
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-py-client
  apiGroup: ""